steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/queenbee:$SHORT_SHA',
        '-t', 'gcr.io/$PROJECT_ID/queenbee:latest',
        '-f', 'docker/base/Dockerfile',
        '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'push',
        'gcr.io/$PROJECT_ID/queenbee:$SHORT_SHA',
    ]
  - name: 'gcr.io/cloud-builders/kubectl'
    env: [
        'CLOUDSDK_COMPUTE_REGION=us-central1',
        'CLOUDSDK_CONTAINER_CLUSTER=logger'
    ]
    args: [
        'patch',
        'deployment', 'queenbee-deployment',
        '-p', '{"spec": {"template": {"spec": {"containers": [{"name": "queenbee","image": "gcr.io/${PROJECT_ID}/queenbee:${SHORT_SHA}"}]}}}}'
    ]

images:
  - 'gcr.io/$PROJECT_ID/queenbee:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/queenbee:latest'

timeout: 1440s
